### ISSUE TITLE
Error message: failed to read payload file: open test/payload.json: no such file or directory

### ISSUE THREAD

**Issue by headcr4sh** [Sydsvenskan/lambda-resource#1]
I am not able to use the param "payload_file" when configuring the lambda-resource in my pipeline.

Excerpt from my pipeline:

```yaml
jobs:
  - name: test-lambda
    plan:
    - get: src # src is a git repository that contains a file called src/test/request.payload.json
    - get: aws-lambda # This is my "lambda-resource" (created/updated in a previous build step)
      params:
        payload_file: src/test/request.payload.json
      trigger: true
```

Unfortunately, the payload_file (even though it exists in my Git repo / resource) is not loaded by the lambda-resource's get step.

I receive an error instead:
```
Error message: failed to read payload file: open src/test/request.payload.json: no such file or directory
```
